package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Condition;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class MainPageTests extends TestBase {
    @Test
    @DisplayName("Project modal form should appear on main page")
    void generatedTest() {
        step("Open url 'https://e-legion.ru'", () ->
                open("https://e-legion.ru"));

        step("Click on top '+' button", () ->
                $(".top__buttons_plus .pulse-button").click()
        );

        step("Project modal form should be visible", () ->
                $(".request .container").shouldBe(visible)
        );
    }

    @Test
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://e-legion.ru'", () ->
                open("https://e-legion.ru"));

        step("Page title should have text 'e-legion — разработка мобильных приложений на заказ. Создание приложений для iPhone, iPad, Android и Windows'", () -> {
            String expectedTitle = "e-legion — разработка мобильных приложений на заказ. Создание приложений для iPhone, iPad, Android и Windows";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://e-legion.ru'", () ->
                open("https://e-legion.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}